// Mocks generated by Mockito 5.0.6 from annotations
// in flutter_app_analytics/test/analytics_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dio/src/dio.dart' as _i2;
import 'package:flutter_app_analytics/src/amplitude_provider.dart' as _i3;
import 'package:flutter_app_analytics/src/analytics_event.dart' as _i6;
import 'package:flutter_app_analytics/src/analytics_identification.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeDio extends _i1.Fake implements _i2.Dio {}

/// A class which mocks [AmplitudeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAmplitudeProvider extends _i1.Mock implements _i3.AmplitudeProvider {
  MockAmplitudeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio())
          as _i2.Dio);
  @override
  set dio(_i2.Dio? _dio) => super.noSuchMethod(Invocation.setter(#dio, _dio),
      returnValueForMissingStub: null);
  @override
  _i4.Future<void> identify(_i5.AnalyticsIdentification? properties) =>
      (super.noSuchMethod(Invocation.method(#identify, [properties]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> trackEvent(_i6.AnalyticsEvent? event) =>
      (super.noSuchMethod(Invocation.method(#trackEvent, [event]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
}
