name: flutter_app_analytics
description: A flutter package to help abstract away vendor specific implementations of in app analytics.
homepage: https://github.com/uptech/flutter_app_analytics
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
flutter:
